name: Upload Python Package

on:
  release:
    types: [ created ]
  workflow_dispatch:
    inputs:
      deploy_to_pypi:
        type: boolean
        description: Deploy the build to PyPI from this manual release.

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/redel
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v3

      # ===== viz =====
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'
          cache-dependency-path: viz/package-lock.json

      - name: Install dependencies
        working-directory: viz
        run: npm i

      - name: Build web interface
        working-directory: viz
        run: npm run build

      # ===== py =====
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
          mkdir dist

      - name: Build
        run: python -m build --sdist --wheel --outdir dist/ .

      - name: Publish to PyPI
        if: startsWith(github.ref, 'refs/tags') || inputs.deploy_to_pypi
        uses: pypa/gh-action-pypi-publish@release/v1
